// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDEItemKeys
    {
        public static string Level_Level1 = "Level1";
        public static string Level_Level2 = "Level2";
        public static string Task_Task1_3 = "Task1_3";
        public static string Task_Task1_2 = "Task1_2";
        public static string Task_Task1_1 = "Task1_1";
        public static string Task_Task2_1 = "Task2_1";
        public static string Task_Task2_2 = "Task2_2";
        public static string Task_Task2_3 = "Task2_3";
        public static string Task_Task2_4 = "Task2_4";
    }
}
